In [74]:
import os
import pandas as pd

In [17]:
df_g = pd.read_csv(f'C:\\Users\\User\Desktop\hdre_t\power_generation.csv')
df_c = pd.read_csv(f'C:\\Users\\User\Desktop\hdre_t\power_consumption.csv')
df_g['時間'], df_c['時間']

(0          2022/1/1 00:15:00
 1          2022/1/1 00:30:00
 2          2022/1/1 00:45:00
 3          2022/1/1 01:00:00
 4          2022/1/1 01:15:00
                 ...
 35035    2022/12/31 23:00:00
 35036    2022/12/31 23:15:00
 35037    2022/12/31 23:30:00
 35038    2022/12/31 23:45:00
 35039      2023/1/1 00:00:00
 Name: 時間, Length: 35040, dtype: object,
 0        2022/01/01 00:15:00
 1        2022/01/01 00:30:00
 2        2022/01/01 00:45:00
 3        2022/01/01 01:00:00
 4        2022/01/01 01:15:00
                 ...
 35035    2022/12/31 23:00:00
 35036    2022/12/31 23:15:00
 35037    2022/12/31 23:30:00
 35038    2022/12/31 23:45:00
 35039    2023/01/01 00:00:00
 Name: 時間, Length: 35040, dtype: object)

In [84]:
df_g = df_g.iloc[3:35043:4]
df_g
# df_g.to_csv('power_generation.csv', encoding='utf-8-sig', index=False)

,時間,電廠001,電廠002,電廠003,電廠004,電廠005,電廠006,電廠007,電廠008,電廠009,...,電廠991,電廠992,電廠993,電廠994,電廠995,電廠996,電廠997,電廠998,電廠999,電廠1000
3,2022/1/1 01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2022/1/1 02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2022/1/1 03:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,2022/1/1 04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,2022/1/1 05:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35023,2022/12/31 20:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35027,2022/12/31 21:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35031,2022/12/31 22:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35035,2022/12/31 23:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35039,2023/1/1 00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [85]:
df_g.to_csv('power_generation.csv', encoding='utf-8-sig', index=False)

In [138]:
new_df_g = pd.read_csv('power_generation.csv')
new_df_g

,時間,電廠001,電廠002,電廠003,電廠004,電廠005,電廠006,電廠007,電廠008,電廠009,...,電廠991,電廠992,電廠993,電廠994,電廠995,電廠996,電廠997,電廠998,電廠999,電廠1000
0,2022/1/1 01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2022/1/1 02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2022/1/1 03:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2022/1/1 04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2022/1/1 05:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022/12/31 20:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8756,2022/12/31 21:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8757,2022/12/31 22:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8758,2022/12/31 23:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8759,2023/1/1 00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [139]:
test = new_df_g.copy()

In [140]:
del test['時間'], new_df_g['時間']
test = test.values * 4
test = pd.DataFrame(test, columns=new_df_g.columns.values)
test

,電廠001,電廠002,電廠003,電廠004,電廠005,電廠006,電廠007,電廠008,電廠009,電廠010,...,電廠991,電廠992,電廠993,電廠994,電廠995,電廠996,電廠997,電廠998,電廠999,電廠1000
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8756,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8757,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8758,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8759,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [142]:
concat_df_g = pd.read_csv('power_generation.csv')
concat_df = pd.concat([concat_df_g['時間'], test], axis=1)
concat_df

,時間,電廠001,電廠002,電廠003,電廠004,電廠005,電廠006,電廠007,電廠008,電廠009,...,電廠991,電廠992,電廠993,電廠994,電廠995,電廠996,電廠997,電廠998,電廠999,電廠1000
0,2022/1/1 01:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2022/1/1 02:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2022/1/1 03:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2022/1/1 04:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2022/1/1 05:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022/12/31 20:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8756,2022/12/31 21:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8757,2022/12/31 22:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8758,2022/12/31 23:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8759,2023/1/1 00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [149]:
import os

filepath = os.path.join(os.getcwd() + os.path.sep + 'hdre_1000_10000_hour')
os.makedirs(filepath, exist_ok=True)
concat_df.to_csv(filepath + os.path.sep + 'power_generation.csv', encoding='utf-8-sig', index=False)

In [1]:
import os
import pandas as pd
df_c = pd.read_csv(f'C:\\Users\\User\Desktop\hdre_t\power_consumption.csv')
df_c

,時間,64-67-0001-13-1,64-67-0002-13-1,64-67-0003-13-1,64-67-0004-13-1,64-67-0005-13-1,64-67-0006-13-1,64-67-0007-13-1,64-67-0008-13-1,64-67-0009-13-1,...,64-67-9991-13-1,64-67-9992-13-1,64-67-9993-13-1,64-67-9994-13-1,64-67-9995-13-1,64-67-9996-13-1,64-67-9997-13-1,64-67-9998-13-1,64-67-9999-13-1,64-67-10000-13-1
0,2022/01/01 00:15:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
1,2022/01/01 00:30:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
2,2022/01/01 00:45:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
3,2022/01/01 01:00:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
4,2022/01/01 01:15:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2022/12/31 23:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35036,2022/12/31 23:15:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35037,2022/12/31 23:30:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35038,2022/12/31 23:45:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35039,2023/01/01 00:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2

In [13]:
tmp_df_c = df_c.copy()
tmp_df = tmp_df_c.iloc[3:35043:4]
tmp_df
# tmp_df.to_csv('power_consumption.csv', encoding='utf-8-sig', index=False)

,時間,64-67-0001-13-1,64-67-0002-13-1,64-67-0003-13-1,64-67-0004-13-1,64-67-0005-13-1,64-67-0006-13-1,64-67-0007-13-1,64-67-0008-13-1,64-67-0009-13-1,...,64-67-9991-13-1,64-67-9992-13-1,64-67-9993-13-1,64-67-9994-13-1,64-67-9995-13-1,64-67-9996-13-1,64-67-9997-13-1,64-67-9998-13-1,64-67-9999-13-1,64-67-10000-13-1
3,2022/01/01 01:00:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
7,2022/01/01 02:00:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
11,2022/01/01 03:00:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
15,2022/01/01 04:00:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
19,2022/01/01 05:00:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35023,2022/12/31 20:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35027,2022/12/31 21:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35031,2022/12/31 22:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35035,2022/12/31 23:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35039,2023/01/01 00:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2

In [11]:
new_time_df = pd.read_csv('power_consumption.csv')

In [14]:
del tmp_df['時間'], new_time_df['時間']
tmp_df = tmp_df.values * 4

final_df = pd.DataFrame(tmp_df, columns=new_time_df.columns.values)
final_df

,64-67-0001-13-1,64-67-0002-13-1,64-67-0003-13-1,64-67-0004-13-1,64-67-0005-13-1,64-67-0006-13-1,64-67-0007-13-1,64-67-0008-13-1,64-67-0009-13-1,64-67-0010-13-1,...,64-67-9991-13-1,64-67-9992-13-1,64-67-9993-13-1,64-67-9994-13-1,64-67-9995-13-1,64-67-9996-13-1,64-67-9997-13-1,64-67-9998-13-1,64-67-9999-13-1,64-67-10000-13-1
0,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,2882.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
1,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,2882.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
2,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,2882.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
3,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,2882.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
4,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,2882.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,3088.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8756,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,3088.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8757,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,3088.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8758,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,3088.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8759,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,3088.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8

In [15]:
concat_df_time = pd.read_csv('power_consumption.csv')
concat_df = pd.concat([concat_df_time['時間'], final_df], axis=1)
concat_df

,時間,64-67-0001-13-1,64-67-0002-13-1,64-67-0003-13-1,64-67-0004-13-1,64-67-0005-13-1,64-67-0006-13-1,64-67-0007-13-1,64-67-0008-13-1,64-67-0009-13-1,...,64-67-9991-13-1,64-67-9992-13-1,64-67-9993-13-1,64-67-9994-13-1,64-67-9995-13-1,64-67-9996-13-1,64-67-9997-13-1,64-67-9998-13-1,64-67-9999-13-1,64-67-10000-13-1
0,2022/01/01 01:00:00,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
1,2022/01/01 02:00:00,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
2,2022/01/01 03:00:00,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
3,2022/01/01 04:00:00,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
4,2022/01/01 05:00:00,392.0,470.4,313.6,1400.0,2258.0,432.8,1042.8,9716.0,252.0,...,3422.0,3739.6,1885.6,11886.0,3276.0,10486.0,3708.4,7994.0,2210.8,4970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022/12/31 20:00:00,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8756,2022/12/31 21:00:00,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8757,2022/12/31 22:00:00,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8758,2022/12/31 23:00:00,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8
8759,2023/01/01 00:00:00,420.0,504.0,336.0,1500.0,2419.2,463.6,1117.2,10410.0,270.0,...,3666.8,4006.8,2020.0,12735.2,3510.0,11235.2,3973.2,8564.8,2368.8,5324.8

In [16]:
import os
filepath = os.path.join(os.getcwd() + os.path.sep + 'hdre_1000_10000_hour')
os.makedirs(filepath, exist_ok=True)
concat_df.to_csv(filepath + os.path.sep + 'power_consumption.csv', encoding='utf-8-sig', index=False)

In [18]:
df = pd.read_csv('./hdre_1000_10000_hour/power_consumption.csv')
df

,時間,64-67-0001-13-1,64-67-0002-13-1,64-67-0003-13-1,64-67-0004-13-1,64-67-0005-13-1,64-67-0006-13-1,64-67-0007-13-1,64-67-0008-13-1,64-67-0009-13-1,...,64-67-9991-13-1,64-67-9992-13-1,64-67-9993-13-1,64-67-9994-13-1,64-67-9995-13-1,64-67-9996-13-1,64-67-9997-13-1,64-67-9998-13-1,64-67-9999-13-1,64-67-10000-13-1
0,2022/1/1 01:00:00,392,470.4,313.6,1400,2258.0,432.8,1042.8,9716,252,...,3422.0,3739.6,1885.6,11886.0,3276,10486.0,3708.4,7994.0,2210.8,4970.0
1,2022/1/1 02:00:00,392,470.4,313.6,1400,2258.0,432.8,1042.8,9716,252,...,3422.0,3739.6,1885.6,11886.0,3276,10486.0,3708.4,7994.0,2210.8,4970.0
2,2022/1/1 03:00:00,392,470.4,313.6,1400,2258.0,432.8,1042.8,9716,252,...,3422.0,3739.6,1885.6,11886.0,3276,10486.0,3708.4,7994.0,2210.8,4970.0
3,2022/1/1 04:00:00,392,470.4,313.6,1400,2258.0,432.8,1042.8,9716,252,...,3422.0,3739.6,1885.6,11886.0,3276,10486.0,3708.4,7994.0,2210.8,4970.0
4,2022/1/1 05:00:00,392,470.4,313.6,1400,2258.0,432.8,1042.8,9716,252,...,3422.0,3739.6,1885.6,11886.0,3276,10486.0,3708.4,7994.0,2210.8,4970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2022/12/31 20:00:00,420,504.0,336.0,1500,2419.2,463.6,1117.2,10410,270,...,3666.8,4006.8,2020.0,12735.2,3510,11235.2,3973.2,8564.8,2368.8,5324.8
8756,2022/12/31 21:00:00,420,504.0,336.0,1500,2419.2,463.6,1117.2,10410,270,...,3666.8,4006.8,2020.0,12735.2,3510,11235.2,3973.2,8564.8,2368.8,5324.8
8757,2022/12/31 22:00:00,420,504.0,336.0,1500,2419.2,463.6,1117.2,10410,270,...,3666.8,4006.8,2020.0,12735.2,3510,11235.2,3973.2,8564.8,2368.8,5324.8
8758,2022/12/31 23:00:00,420,504.0,336.0,1500,2419.2,463.6,1117.2,10410,270,...,3666.8,4006.8,2020.0,12735.2,3510,11235.2,3973.2,8564.8,2368.8,5324.8
8759,2023/1/1 00:00:00,420,504.0,336.0,1500,2419.2,463.6,1117.2,10410,270,...,3666.8,4006.8,2020.0,12735.2,3510,11235.2,3973.2,8564.8,2368.8,5324.8

In [19]:
df_1 = pd.read_csv(f'C:\\Users\\User\Desktop\hdre_t\power_consumption.csv')
df_1

,時間,64-67-0001-13-1,64-67-0002-13-1,64-67-0003-13-1,64-67-0004-13-1,64-67-0005-13-1,64-67-0006-13-1,64-67-0007-13-1,64-67-0008-13-1,64-67-0009-13-1,...,64-67-9991-13-1,64-67-9992-13-1,64-67-9993-13-1,64-67-9994-13-1,64-67-9995-13-1,64-67-9996-13-1,64-67-9997-13-1,64-67-9998-13-1,64-67-9999-13-1,64-67-10000-13-1
0,2022/01/01 00:15:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
1,2022/01/01 00:30:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
2,2022/01/01 00:45:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
3,2022/01/01 01:00:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
4,2022/01/01 01:15:00,98.0,117.6,78.4,350.0,564.5,108.2,260.7,2429.0,63.0,...,855.5,934.9,471.4,2971.5,819.0,2621.5,927.1,1998.5,552.7,1242.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2022/12/31 23:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35036,2022/12/31 23:15:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35037,2022/12/31 23:30:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35038,2022/12/31 23:45:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2
35039,2023/01/01 00:00:00,105.0,126.0,84.0,375.0,604.8,115.9,279.3,2602.5,67.5,...,916.7,1001.7,505.0,3183.8,877.5,2808.8,993.3,2141.2,592.2,1331.2

In [20]:
df.sum()

時間                  2022/1/1 01:00:002022/1/1 02:00:002022/1/1 03:...
64-67-0001-13-1                                               8174392
64-67-0002-13-1                                             9809270.4
64-67-0003-13-1                                             6539513.6
64-67-0004-13-1                                              14630400
                                          ...
64-67-9996-13-1                                           109581984.0
64-67-9997-13-1                                            77329890.8
64-67-9998-13-1                                            83539296.0
64-67-9999-13-1                                            46103582.4
64-67-10000-13-1                                           51937632.0
Length: 10001, dtype: object

In [22]:
df_1.sum()

時間                  2022/01/01 00:15:002022/01/01 00:30:002022/01/...
64-67-0001-13-1                                             8130250.0
64-67-0002-13-1                                             9756300.0
64-67-0003-13-1                                             6504200.0
64-67-0004-13-1                                            14630400.0
                                          ...
64-67-9996-13-1                                           109581984.0
64-67-9997-13-1                                            76912346.7
64-67-9998-13-1                                            83539296.0
64-67-9999-13-1                                            45854621.2
64-67-10000-13-1                                           51937632.0
Length: 10001, dtype: object